# Generated by Django 3.0.5 on 2020-04-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200409_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='in_stock',
        ),
    ]
